#!/bin/bash

set -x

export MPIAUTOCONFIG="/home/gmap/mrpm/marguina/.mpiautorc/mpiauto.TIME.conf"

/home/gmap/mrpm/marguina/SAVE/mpiauto/mpiauto --nouse-slurm-mpi --verbose --wrap --wrap-stdeo $*

set +x
