#!/bin/bash

function module { eval `/usr/bin/modulecmd bash $*`; }

module purge 2>/dev/null
module load intel/2018.5.274_mkl_nightly_2019u2 2>/dev/null
module load gcc/5.3.0 2>/dev/null

export TMP=/tmp
export LD_LIBRARY_WRAP=$(echo $LD_LIBRARY_PATH | sed -e "s/:/ -Wl,-rpath,/g" -e "s/^/-Wl,-rpath,/")
